[package]
name = "mandate"
version = "0.1.0"
description = "Mandate: escrow, bids, attested epochs and exact reward settlement"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "mandate"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "1.2.0", features = ["init-if-needed"] }
anchor-spl = "1.2.0"
mandate-core = { path = "../../crates/mandate-core" }

[lints]
workspace = true
