import { readFileSync } from "node:fs";
import { PublicKey } from "@solana/web3.js";
import { describe, expect, it } from "vitest";

import {
  MANDATE_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  acceptAdmin,
  acceptBid,
  activateMandate,
  findPositionSetPda,
  refundUnactivatedMandate,
  registerPositions,
  cancelBid,
  closeBid,
  claimProviderReward,
  closeMandate,
  finalizeEpoch,
  finalizeUnavailableEpoch,
  findEpochResultPda,
  findAttestationPda,
  findBidPda,
  submitAttestation,
  submitBid,
  withdrawSurplusAfterAward,
  buildInstruction,
  cancelAdminTransfer,
  cancelUnawardedMandate,
  createMandate,
  createObserverSet,
  findMandatePda,
  findMarketPda,
  findObserverSetPda,
  findProgramDataPda,
  findProtocolPda,
  findVaultPda,
  initializeProtocol,
  proposeAdmin,
  setMarketEnabled,
  setPausedNewRisk,
  upsertMarket,
} from "../src/index.ts";

interface Vectors {
  readonly programId: string;
  readonly keys: Record<"sponsor" | "admin" | "pool" | "baseMint" | "usdcMint", string>;
  readonly pdas: Record<string, string>;
  readonly instructions: readonly {
    readonly instruction: string;
    readonly accounts: readonly { pubkey: string; isSigner: boolean; isWritable: boolean }[];
    readonly dataHex: string;
  }[];
}

// Generated by the Rust program tests from the compiled program's own types (crates/program-tests).
const vectors = JSON.parse(
  readFileSync(new URL("../vectors/client-vectors.json", import.meta.url), "utf8"),
) as Vectors;

const filled = (n: number): PublicKey => new PublicKey(new Uint8Array(32).fill(n));
const key = (text: string): PublicKey => new PublicKey(text);
const k = vectors.keys;
const sponsor = key(k.sponsor);
const admin = key(k.admin);
const pool = key(k.pool);
const baseMint = key(k.baseMint);
const usdcMint = key(k.usdcMint);

function expectMatch(
  name: string,
  built: { keys: { pubkey: PublicKey; isSigner: boolean; isWritable: boolean }[]; data: Buffer },
): void {
  const expected = vectors.instructions.find((i) => i.instruction === name);
  if (!expected) throw new Error(`no Rust vector for ${name}`);
  expect(built.data.toString("hex"), `${name} data`).toBe(expected.dataHex);
  expect(
    built.keys.map((a) => ({
      pubkey: a.pubkey.toBase58(),
      isSigner: a.isSigner,
      isWritable: a.isWritable,
    })),
    `${name} accounts`,
  ).toEqual(expected.accounts);
}

describe("the TypeScript client agrees with the Rust program", () => {
  it("uses the same program id", () => {
    expect(MANDATE_PROGRAM_ID.toBase58()).toBe(vectors.programId);
  });

  it("derives every PDA identically", () => {
    expect(findProtocolPda().toBase58()).toBe(vectors.pdas["protocol"]);
    expect(findObserverSetPda(1).toBase58()).toBe(vectors.pdas["observerSetV1"]);
    expect(findObserverSetPda(2).toBase58()).toBe(vectors.pdas["observerSetV2"]);
    expect(findMarketPda(pool).toBase58()).toBe(vectors.pdas["market"]);
    expect(findMandatePda(sponsor, 42n).toBase58()).toBe(vectors.pdas["mandate42"]);
    expect(findVaultPda(findMandatePda(sponsor, 42n)).toBase58()).toBe(vectors.pdas["vault42"]);
    expect(findProgramDataPda().toBase58()).toBe(vectors.pdas["programData"]);
  });

  it("encodes initialize_protocol", () => {
    expectMatch(
      "initialize_protocol",
      initializeProtocol({
        payer: filled(6),
        upgradeAuthority: filled(7),
        usdcMint,
        terms: {
          admin,
          dlmmProgram: filled(9),
          minBudgetRaw: 1_000n,
          maxBudgetRaw: 1_000_000_000_000n,
          minEpochSeconds: 60n,
          maxEpochSeconds: 3_600n,
          maxDurationSeconds: 2_592_000n,
          maxEpochs: 2_016,
          maxSpreadBps: 1_000,
          maxDepthBandBps: 2_000,
          maxPositions: 8,
          minProbeQuoteRaw: 1_000_000n,
          maxProbeQuoteRaw: 1_000_000_000n,
          minStartLeadSeconds: 1_200n,
          positionLockBufferSeconds: 300n,
          minSetupWindowSeconds: 600n,
          unavailableRecoverySeconds: 3_600n,
        },
      }),
    );
  });

  it("encodes the admin instructions", () => {
    expectMatch("propose_admin", proposeAdmin({ admin, newAdmin: filled(8) }));
    expectMatch("cancel_admin_transfer", cancelAdminTransfer({ admin }));
    expectMatch("set_paused_new_risk", setPausedNewRisk({ admin, paused: true }));
    expectMatch("accept_admin", acceptAdmin({ pendingAdmin: filled(8) }));
  });

  it("encodes create_observer_set, upsert_market and set_market_enabled", () => {
    expectMatch(
      "create_observer_set",
      createObserverSet({
        admin,
        observers: [filled(10), filled(11), filled(12)],
        threshold: 2,
        nextVersion: 1,
      }),
    );
    expectMatch(
      "upsert_market",
      upsertMarket({
        admin,
        pool,
        baseMint,
        quoteMint: usdcMint,
        prestocksMetadataHash: new Uint8Array(32).fill(7),
      }),
    );
    expectMatch("set_market_enabled", setMarketEnabled({ admin, pool, enabled: true }));
  });

  it("encodes create_mandate and cancel_unawarded_mandate", () => {
    expectMatch(
      "create_mandate",
      createMandate({
        sponsor,
        sponsorUsdc: filled(13),
        pool,
        usdcMint,
        observerSetVersion: 1,
        terms: {
          mandateId: 42n,
          maxRewardRaw: 1_000_000_000n,
          biddingEndsAt: 1_789_925_436n,
          startAt: 1_789_929_036n,
          durationSeconds: 21_600n,
          epochSeconds: 300n,
          maxEffectiveSpreadBps: 400,
          depthBandBps: 500,
          minPoolBuyDepthQuoteRaw: 8_000_000_000n,
          minPoolSellDepthQuoteRaw: 8_000_000_000n,
          minProviderQuoteInBandRaw: 5_000_000_000n,
          minProviderBaseQuoteEqInBandRaw: 5_000_000_000n,
          probeQuoteRaw: 10_000_000n,
        },
      }),
    );
    expectMatch(
      "cancel_unawarded_mandate",
      cancelUnawardedMandate({ sponsor, sponsorUsdc: filled(13), mandateId: 42n, usdcMint }),
    );
  });

  it("encodes the bidding and award instructions", () => {
    const provider = filled(14);
    const mandate = findMandatePda(sponsor, 42n);
    expect(findBidPda(mandate, provider, 3n).toBase58()).toBe(vectors.pdas["bid42x14n3"]);
    expectMatch(
      "submit_bid",
      submitBid({
        provider,
        mandate,
        nonce: 3n,
        requestedRewardRaw: 900_000_001n,
        validUntil: 1_789_926_836n,
      }),
    );
    expectMatch("cancel_bid", cancelBid({ provider, mandate, nonce: 3n }));
    expectMatch("close_bid", closeBid({ provider, mandate, nonce: 3n }));
    expectMatch("accept_bid", acceptBid({ sponsor, mandate, provider, nonce: 3n }));
    expectMatch(
      "withdraw_surplus_after_award",
      withdrawSurplusAfterAward({
        sponsor,
        sponsorUsdc: filled(13),
        mandate,
        usdcMint,
        amountRaw: 99_999_999n,
      }),
    );
  });

  it("encodes registration, activation and the unactivated refund", () => {
    const provider = filled(14);
    const mandate = findMandatePda(sponsor, 42n);
    expect(findPositionSetPda(mandate).toBase58()).toBe(vectors.pdas["positionSet42"]);
    expectMatch(
      "register_positions",
      registerPositions({ provider, mandate, positions: [filled(20), filled(21), filled(22)] }),
    );
    expectMatch("activate_mandate", activateMandate({ mandate }));
    expectMatch(
      "refund_unactivated_mandate",
      refundUnactivatedMandate({ sponsor, sponsorUsdc: filled(13), mandate, usdcMint }),
    );
  });

  it("encodes submit_attestation and derives its PDA identically", () => {
    const observer = filled(30);
    const mandate = findMandatePda(sponsor, 42n);
    expect(findAttestationPda(mandate, 7, observer).toBase58()).toBe(
      vectors.pdas["attestation42e7o30"],
    );
    expectMatch(
      "submit_attestation",
      submitAttestation({
        observer,
        mandate,
        observerSet: findObserverSetPda(1),
        positionSet: findPositionSetPda(mandate),
        terms: {
          epochIndex: 7,
          observedSlot: 448_786_149n,
          observedUnixTs: 1_789_921_836n,
          algorithmVersion: 1,
          payloadHash: new Uint8Array(32).fill(0xaa),
          evidenceHash: new Uint8Array(32).fill(0xbb),
          metrics: {
            effectiveSpreadBps: 251,
            poolBuyDepthQuoteRaw: 63_491_020_966n,
            poolSellDepthQuoteRaw: 49_065_543_907n,
            providerQuoteInBandRaw: 91_107_867n,
            providerBaseQuoteEqInBandRaw: 81_314_309n,
          },
        },
      }),
    );
  });

  it("encodes epoch finalization, claims and closing identically", () => {
    const mandate = findMandatePda(sponsor, 42n);
    const observers = [filled(30), filled(32)];
    expect(findEpochResultPda(mandate, 7).toBase58()).toBe(vectors.pdas["epochResult42e7"]);
    expectMatch(
      "finalize_epoch",
      finalizeEpoch({
        payer: filled(31),
        mandate,
        observerSet: findObserverSetPda(1),
        positionSet: findPositionSetPda(mandate),
        epochIndex: 7,
        attestations: observers.map((o) => findAttestationPda(mandate, 7, o)),
      }),
    );
    expectMatch(
      "finalize_unavailable_epoch",
      finalizeUnavailableEpoch({ payer: filled(31), mandate, epochIndex: 7 }),
    );
    expectMatch(
      "claim_provider_reward",
      claimProviderReward({
        provider: filled(14),
        providerUsdc: filled(15),
        mandate,
        usdcMint,
        amountRaw: 12_500_000n,
      }),
    );
    expectMatch("close_mandate", closeMandate({ caller: filled(31), mandate, sponsor, usdcMint }));
  });

  it("covers every instruction the Rust side produced a vector for", () => {
    expect(vectors.instructions.map((i) => i.instruction).sort()).toEqual(
      [
        "accept_admin",
        "cancel_admin_transfer",
        "cancel_unawarded_mandate",
        "create_mandate",
        "create_observer_set",
        "initialize_protocol",
        "propose_admin",
        "set_market_enabled",
        "set_paused_new_risk",
        "upsert_market",
        "submit_bid",
        "cancel_bid",
        "close_bid",
        "accept_bid",
        "withdraw_surplus_after_award",
        "register_positions",
        "activate_mandate",
        "refund_unactivated_mandate",
        "submit_attestation",
        "finalize_epoch",
        "finalize_unavailable_epoch",
        "claim_provider_reward",
        "close_mandate",
      ].sort(),
    );
  });
});

describe("builder safety", () => {
  it("rejects a missing account", () => {
    expect(() => buildInstruction("propose_admin", { newAdmin: filled(1) }, { admin })).toThrow(
      /missing account protocol/,
    );
  });

  it("rejects an unexpected account", () => {
    expect(() =>
      buildInstruction(
        "propose_admin",
        { newAdmin: filled(1) },
        { admin, protocol: findProtocolPda(), extra: filled(2) },
      ),
    ).toThrow(/unexpected accounts extra/);
  });

  it("rejects an unknown instruction", () => {
    expect(() => buildInstruction("drain_vault", {}, {})).toThrow(/unknown instruction/);
  });

  it("fills fixed program accounts from the IDL, so they cannot be spoofed", () => {
    const ix = cancelAdminTransfer({ admin });
    expect(ix.keys.map((a) => a.pubkey.toBase58())).not.toContain(TOKEN_PROGRAM_ID.toBase58());
    const create = createObserverSet({
      admin,
      observers: [filled(10)],
      threshold: 1,
      nextVersion: 1,
    });
    expect(create.keys.at(-1)?.pubkey.toBase58()).toBe("11111111111111111111111111111111");
  });

  it("marks signers and writable accounts exactly as the program requires", () => {
    const ix = createMandate({
      sponsor,
      sponsorUsdc: filled(13),
      pool,
      usdcMint,
      observerSetVersion: 1,
      terms: {
        mandateId: 1n,
        maxRewardRaw: 1n,
        biddingEndsAt: 1n,
        startAt: 1n,
        durationSeconds: 1n,
        epochSeconds: 1n,
        maxEffectiveSpreadBps: 1,
        depthBandBps: 1,
        minPoolBuyDepthQuoteRaw: 1n,
        minPoolSellDepthQuoteRaw: 1n,
        minProviderQuoteInBandRaw: 1n,
        minProviderBaseQuoteEqInBandRaw: 1n,
        probeQuoteRaw: 1n,
      },
    });
    const byName = Object.fromEntries(ix.keys.map((a) => [a.pubkey.toBase58(), a]));
    expect(byName[sponsor.toBase58()]).toMatchObject({ isSigner: true, isWritable: true });
    expect(byName[findProtocolPda().toBase58()]).toMatchObject({
      isSigner: false,
      isWritable: false,
    });
  });
});

describe("PDA argument validation", () => {
  it("rejects out-of-range integers instead of wrapping", () => {
    expect(() => findObserverSetPda(-1)).toThrow(RangeError);
    expect(() => findObserverSetPda(2 ** 32)).toThrow(RangeError);
    expect(() => findMandatePda(sponsor, -1n)).toThrow(RangeError);
    expect(() => findMandatePda(sponsor, 2n ** 64n)).toThrow(RangeError);
    expect(findMandatePda(sponsor, 2n ** 64n - 1n)).toBeInstanceOf(PublicKey);
  });
});
